### ISSUE TITLE
[gcloud-sqlproxy] Use instanceShortName (if specified) for service port name

### ISSUE THREAD

**Issue by karsthammer** [rimusz/charts#81]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:

**Which chart**:
gcloud-sqlproxy

**What happened**:
I'm trying to deploy the chart and defining 2 SQL instances that are in different projects but having the same instance name. The deployment failed with the following message:

```
Service "x" is invalid: spec.ports[5].name: Duplicate value: "x-consultation"
```

Even with the `instanceShortName` set it still uses the original instance name for naming the port in the service object.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

```yaml
cloudsql:
  instances:
    - project: project-1
      region: europe-west1
      instance: abc-consultation
      instanceShortName: abc-consult-stg
      port: 3309
    - project: project-2
      region: europe-west1
      instance: abc-consultation
      instanceShortName: abc-consult-prd
      port: 3310
```

**Anything else we need to know**:

This might be fixable by also using the `instanceShortName` (when available) in the `svc.yaml` for naming the port.
